# GENERATED by scripts/sync_api_contracts.py from apps/api/src/lib/error-reasons.ts.
# Do not edit by hand: run `python scripts/sync_api_contracts.py` in packages/sdk-python.

from __future__ import annotations

from typing import Dict, Literal, Tuple, TypedDict


class ReasonDefinition(TypedDict):
    """What a reason means and what to do next, as the API documents it."""

    status: int
    summary: str
    action: str


ErrorReason = Literal[
    "INVALID_PARAMETER",
    "INVALID_JSON",
    "INVALID_REQUEST",
    "AUTH_REQUIRED",
    "KEY_MISSING",
    "KEY_INVALID",
    "KEY_DISABLED",
    "KEY_EXPIRED",
    "SIGN_IN_REQUIRED",
    "SESSION_EXPIRED",
    "ACCOUNT_NOT_FOUND",
    "LINK_EXPIRED",
    "PROXY_CREDENTIAL_INVALID",
    "PLAN_REQUIRED",
    "ACCOUNT_SUSPENDED",
    "KEY_NOT_LINKED_TO_ACCOUNT",
    "KEY_NOT_LINKED_TO_SHOP",
    "SHOP_UNDER_REVIEW",
    "NOT_OWNER",
    "PURCHASE_REQUIRED",
    "LIMIT_REACHED",
    "PAGINATION_DEPTH_EXCEEDED",
    "ADMIN_REQUIRED",
    "READ_ONLY_SESSION",
    "ORIGIN_BLOCKED",
    "CLIENT_BLOCKED",
    "ACTION_NOT_ALLOWED",
    "RESOURCE_NOT_FOUND",
    "ROUTE_NOT_FOUND",
    "CONFLICT",
    "PAYLOAD_TOO_LARGE",
    "RATE_LIMITED",
    "DAILY_CAP_EXCEEDED",
    "MCP_DAILY_CAP_EXCEEDED",
    "PAGINATION_BURST",
    "REPORT_RATE_LIMITED",
    "INTERNAL_ERROR",
    "DEPENDENCY_UNAVAILABLE",
    "MAINTENANCE",
]
"""Every ``error.reason`` the API can send.

``code`` names the family (``UNAUTHORIZED``, ``FORBIDDEN``) and never changes;
``reason`` names the situation, and the fix for each is different. A reason is
part of the published contract: new ones are added, none is renamed.
"""

ERROR_REASONS: Dict[str, ReasonDefinition] = {
    "INVALID_PARAMETER": {
        "status": 400,
        "summary": 'A path, query or body field failed validation. `details` names each field and what was wrong with it.',
        "action": 'Correct the named fields and send the request again.',
    },
    "INVALID_JSON": {
        "status": 400,
        "summary": 'The request body is not valid JSON.',
        "action": 'Send a JSON body with `Content-Type: application/json`.',
    },
    "INVALID_REQUEST": {
        "status": 400,
        "summary": 'The request is well-formed but asks for something the endpoint refuses; the message says what.',
        "action": 'Change the request as the message describes.',
    },
    "AUTH_REQUIRED": {
        "status": 401,
        "summary": 'This endpoint needs a credential and none was sent.',
        "action": 'Send an API key in `X-API-Key`, or sign in.',
    },
    "KEY_MISSING": {
        "status": 401,
        "summary": 'No API key was sent.',
        "action": 'Send your key in the `X-API-Key` header.',
    },
    "KEY_INVALID": {
        "status": 401,
        "summary": 'The API key is not one we issued, or it has been deleted.',
        "action": 'Check the key for a typo, or create a new one in your account.',
    },
    "KEY_DISABLED": {
        "status": 401,
        "summary": 'The key was switched off by the account that owns it.',
        "action": 'Re-enable it in your account, or use another key.',
    },
    "KEY_EXPIRED": {
        "status": 401,
        "summary": 'The key has passed its expiry date.',
        "action": 'Create a new key in your account.',
    },
    "SIGN_IN_REQUIRED": {
        "status": 401,
        "summary": 'This endpoint needs a signed-in session.',
        "action": 'Sign in, then retry.',
    },
    "SESSION_EXPIRED": {
        "status": 401,
        "summary": 'The session is no longer valid.',
        "action": 'Sign in again.',
    },
    "ACCOUNT_NOT_FOUND": {
        "status": 401,
        "summary": 'The credential verified, but the account behind it no longer exists.',
        "action": 'Sign in again, or contact support.',
    },
    "LINK_EXPIRED": {
        "status": 401,
        "summary": 'The one-time access link has expired or was already used.',
        "action": 'Request a new link.',
    },
    "PROXY_CREDENTIAL_INVALID": {
        "status": 401,
        "summary": 'A proxy or marketplace credential was presented and does not verify.',
        "action": 'Through a marketplace such as RapidAPI, contact the API provider: the proxy is misconfigured.',
    },
    "PLAN_REQUIRED": {
        "status": 403,
        "summary": 'The credential is valid and its plan is below what this endpoint needs. `details.requiredTier` names the plan.',
        "action": 'Upgrade the plan. A new key on the same plan will get the same answer.',
    },
    "ACCOUNT_SUSPENDED": {
        "status": 403,
        "summary": 'The account behind this credential has been suspended.',
        "action": 'Contact support. Rotating the key will not help.',
    },
    "KEY_NOT_LINKED_TO_ACCOUNT": {
        "status": 403,
        "summary": 'The key is valid but no user account owns it, so account endpoints (`/v1/me`) have nothing to act on.',
        "action": 'Use a key created from your account.',
    },
    "KEY_NOT_LINKED_TO_SHOP": {
        "status": 403,
        "summary": 'The key is valid but no shop names it, so seller endpoints (`/v1/vendor`) have no shop to act for.',
        "action": 'Name the key in Profile > Seller on the shop it should act for, then check `GET /v1/vendor/shops`.',
    },
    "SHOP_UNDER_REVIEW": {
        "status": 403,
        "summary": 'The shop exists and has not been approved yet.',
        "action": 'Wait for approval. Nothing needs to be sent again.',
    },
    "NOT_OWNER": {
        "status": 403,
        "summary": 'The resource exists and belongs to another account or shop.',
        "action": 'Use an id your account owns.',
    },
    "PURCHASE_REQUIRED": {
        "status": 403,
        "summary": 'The download belongs to a product this account has not bought.',
        "action": 'Buy the product, then retry.',
    },
    "LIMIT_REACHED": {
        "status": 403,
        "summary": "The plan's allowance for this kind of item is used up.",
        "action": 'Remove one, or upgrade for a larger allowance.',
    },
    "PAGINATION_DEPTH_EXCEEDED": {
        "status": 403,
        "summary": 'The plan does not page this deep into a list.',
        "action": 'Narrow the list with filters, or upgrade for deeper paging.',
    },
    "ADMIN_REQUIRED": {
        "status": 403,
        "summary": 'Staff-only endpoint.',
        "action": 'Sign in with a staff account.',
    },
    "READ_ONLY_SESSION": {
        "status": 403,
        "summary": 'This is an impersonation session, which may look but never change anything.',
        "action": 'Make the change from your own account.',
    },
    "ORIGIN_BLOCKED": {
        "status": 403,
        "summary": 'A browser request carried a GunSpec origin without the signature our own apps send.',
        "action": 'Call the API with an API key.',
    },
    "CLIENT_BLOCKED": {
        "status": 403,
        "summary": 'This client, user agent or address is blocked.',
        "action": 'Contact support if you think this is a mistake.',
    },
    "ACTION_NOT_ALLOWED": {
        "status": 403,
        "summary": 'The action is not permitted on this resource; the message says why.',
        "action": 'Do not retry unchanged.',
    },
    "RESOURCE_NOT_FOUND": {
        "status": 404,
        "summary": 'The path is right and no record has that id.',
        "action": 'Check the id. The list and search endpoints return valid ones.',
    },
    "ROUTE_NOT_FOUND": {
        "status": 404,
        "summary": 'No endpoint answers this method and path.',
        "action": 'Check the path and method against the API reference.',
    },
    "CONFLICT": {
        "status": 409,
        "summary": 'The request conflicts with existing data, such as a slug already in use.',
        "action": 'Change the conflicting value and retry.',
    },
    "PAYLOAD_TOO_LARGE": {
        "status": 413,
        "summary": 'The request body is larger than this endpoint accepts. `maxBytes` carries the limit.',
        "action": 'Split the request into smaller ones.',
    },
    "RATE_LIMITED": {
        "status": 429,
        "summary": 'Too many requests this minute for the plan.',
        "action": 'Wait for `Retry-After` seconds, then retry.',
    },
    "DAILY_CAP_EXCEEDED": {
        "status": 429,
        "summary": "The plan's daily request allowance is used up. It resets at midnight UTC.",
        "action": 'Wait for the reset, or upgrade for a larger allowance.',
    },
    "MCP_DAILY_CAP_EXCEEDED": {
        "status": 429,
        "summary": "The plan's daily allowance for calls through the MCP server is used up. It resets at midnight UTC; direct API requests still count against the plan's own allowance.",
        "action": 'Wait for the reset, call the API directly, or upgrade for a larger MCP allowance.',
    },
    "PAGINATION_BURST": {
        "status": 429,
        "summary": 'Too many sequential pages in a short time.',
        "action": 'Slow the walk down, or use a larger `per_page`.',
    },
    "REPORT_RATE_LIMITED": {
        "status": 429,
        "summary": 'A data report for this section was already filed in the last 24 hours.',
        "action": 'Wait a day, or add to the report already filed.',
    },
    "INTERNAL_ERROR": {
        "status": 500,
        "summary": 'Something failed on our side. It has been logged against `request_id`.',
        "action": 'Retry with backoff. Quote `request_id` if it persists.',
    },
    "DEPENDENCY_UNAVAILABLE": {
        "status": 503,
        "summary": 'A service this endpoint depends on is temporarily unavailable.',
        "action": 'Retry after a short wait.',
    },
    "MAINTENANCE": {
        "status": 503,
        "summary": 'The API is paused for maintenance.',
        "action": 'Wait for `Retry-After` seconds, then retry.',
    },
}

ERROR_REASON_NAMES: Tuple[str, ...] = tuple(ERROR_REASONS)


def is_error_reason(value: object) -> bool:
    """Whether ``value`` is a reason the SDK recognises."""
    return isinstance(value, str) and value in ERROR_REASONS
