# GENERATED by scripts/sync_api_contracts.py from apps/api/src/config/vocab.ts.
# Do not edit by hand: run `python scripts/sync_api_contracts.py` in packages/sdk-python.

"""Every closed vocabulary the API serves, one Literal and one tuple each.

The spec publishes each as a named component and references it wherever the
value appears; the models use these Literals so a value the API can send is
one a caller can branch on.
"""

from __future__ import annotations

from typing import Literal, Tuple

FirearmStatus = Literal[
    "in_production",
    "discontinued",
    "out_of_production",
    "in_service",
    "limited_production",
    "prototype",
]
"""Production status of a firearm. Closed: these are every value the catalog holds."""

FIREARM_STATUSES: Tuple[FirearmStatus, ...] = (
    "in_production",
    "discontinued",
    "out_of_production",
    "in_service",
    "limited_production",
    "prototype",
)

FirearmActionType = Literal[
    "short_recoil",
    "bolt_action",
    "blowback",
    "break_action",
    "gas_operated",
    "gas_operated_long_stroke",
    "gas_operated_direct_impingement",
    "revolving",
    "gas_operated_short_stroke",
    "muzzleloader",
    "pump_action",
    "lever_action",
    "double_action",
    "falling_block",
    "roller_delayed_blowback",
    "single_action",
    "gas_operated_short_stroke_piston",
    "single_action_revolver",
    "double_action_revolver",
    "inertia_operated",
    "recoil_operated",
    "delayed_blowback",
    "long_recoil",
    "gas_operated_rotating_bolt",
    "breech_loading",
    "rolling_block",
    "straight_pull",
    "trapdoor",
    "spring_piston",
    "hinged_breechblock",
    "lever_delayed_blowback",
    "blow_forward",
    "electric_gatling",
    "double_action_only",
    "rotating_barrel",
    "pneumatic",
    "gas_operated_dual_mode",
    "delayed_blowback_rotating_barrel",
    "gas_delayed_blowback",
    "radial_delayed_blowback",
    "short_recoil_rotating_barrel",
    "gas_operated_balanced_automatics",
    "gas_operated_balanced_recoil",
    "gas_operated_blow_forward",
    "gas_operated_open_bolt",
    "gas_operated_tilting_bolt",
]
"""In descending order of how often each occurs in the catalog."""

FIREARM_ACTION_TYPES: Tuple[FirearmActionType, ...] = (
    "short_recoil",
    "bolt_action",
    "blowback",
    "break_action",
    "gas_operated",
    "gas_operated_long_stroke",
    "gas_operated_direct_impingement",
    "revolving",
    "gas_operated_short_stroke",
    "muzzleloader",
    "pump_action",
    "lever_action",
    "double_action",
    "falling_block",
    "roller_delayed_blowback",
    "single_action",
    "gas_operated_short_stroke_piston",
    "single_action_revolver",
    "double_action_revolver",
    "inertia_operated",
    "recoil_operated",
    "delayed_blowback",
    "long_recoil",
    "gas_operated_rotating_bolt",
    "breech_loading",
    "rolling_block",
    "straight_pull",
    "trapdoor",
    "spring_piston",
    "hinged_breechblock",
    "lever_delayed_blowback",
    "blow_forward",
    "electric_gatling",
    "double_action_only",
    "rotating_barrel",
    "pneumatic",
    "gas_operated_dual_mode",
    "delayed_blowback_rotating_barrel",
    "gas_delayed_blowback",
    "radial_delayed_blowback",
    "short_recoil_rotating_barrel",
    "gas_operated_balanced_automatics",
    "gas_operated_balanced_recoil",
    "gas_operated_blow_forward",
    "gas_operated_open_bolt",
    "gas_operated_tilting_bolt",
)

FirearmFiringMechanism = Literal[
    "striker_fired",
    "hammer_fired",
    "double_action",
    "double_action_only",
    "single_action",
    "double_action_single_action",
    "open_bolt",
    "closed_bolt",
    "rotating_bolt",
    "internal_hammer",
    "fixed_firing_pin",
    "flintlock",
    "matchlock",
    "wheellock",
    "miquelet_lock",
    "percussion",
    "percussion_cap",
    "single_action_only",
    "traditional_double_action",
    "solenoid_fired",
    "externally_powered",
    "hammerless",
    "pneumatic",
]
"""How the round is set off."""

FIREARM_FIRING_MECHANISMS: Tuple[FirearmFiringMechanism, ...] = (
    "striker_fired",
    "hammer_fired",
    "double_action",
    "double_action_only",
    "single_action",
    "double_action_single_action",
    "open_bolt",
    "closed_bolt",
    "rotating_bolt",
    "internal_hammer",
    "fixed_firing_pin",
    "flintlock",
    "matchlock",
    "wheellock",
    "miquelet_lock",
    "percussion",
    "percussion_cap",
    "single_action_only",
    "traditional_double_action",
    "solenoid_fired",
    "externally_powered",
    "hammerless",
    "pneumatic",
)

FirearmTriggerType = Literal[
    "safe_action",
    "single_stage",
    "single_action",
    "two_stage",
    "double_action",
    "double_action_single_action",
    "da_sa",
    "set_trigger",
    "progressive_two_stage",
    "select_fire",
    "automatic",
    "automatic_only",
    "full_auto_only",
    "semi_auto",
    "flat_faced",
    "single_action_with_restrike",
    "double_trigger",
    "single_trigger",
    "double_action_only",
    "single_action_only",
    "single_selective",
    "selective_fire",
    "double_set",
    "single_set",
    "striker_fired",
    "adjustable",
    "adjustable_single_stage",
    "adjustable_two_stage",
    "adjustable_match",
    "two_stage_adjustable_match",
    "quattro_two_stage_adjustable",
    "match",
    "progressive",
    "electronic",
    "contact_fire",
    "strike_two",
    "flat_face_safe_action",
    "sheathed_trigger",
    "self_defense_trigger",
    "concealed_hammer",
    "internal_hammer",
    "ring_trigger",
    "spade_grip",
    "thumb_triggers",
]
"""What the trigger does, as distinct from what sets the round off."""

FIREARM_TRIGGER_TYPES: Tuple[FirearmTriggerType, ...] = (
    "safe_action",
    "single_stage",
    "single_action",
    "two_stage",
    "double_action",
    "double_action_single_action",
    "da_sa",
    "set_trigger",
    "progressive_two_stage",
    "select_fire",
    "automatic",
    "automatic_only",
    "full_auto_only",
    "semi_auto",
    "flat_faced",
    "single_action_with_restrike",
    "double_trigger",
    "single_trigger",
    "double_action_only",
    "single_action_only",
    "single_selective",
    "selective_fire",
    "double_set",
    "single_set",
    "striker_fired",
    "adjustable",
    "adjustable_single_stage",
    "adjustable_two_stage",
    "adjustable_match",
    "two_stage_adjustable_match",
    "quattro_two_stage_adjustable",
    "match",
    "progressive",
    "electronic",
    "contact_fire",
    "strike_two",
    "flat_face_safe_action",
    "sheathed_trigger",
    "self_defense_trigger",
    "concealed_hammer",
    "internal_hammer",
    "ring_trigger",
    "spade_grip",
    "thumb_triggers",
)

FirearmMagazineType = Literal[
    "detachable_box",
    "detachable_single_stack_box",
    "fixed_box",
    "internal",
    "drum",
    "belt",
    "belt_fed",
    "disintegrating_link_belt",
    "tube",
    "tubular",
    "dual_tubular",
    "rotary",
    "revolving_cylinder",
    "helical",
    "en_bloc_clip",
    "stripper_clip",
    "internal_box",
    "integral",
    "feed_strip",
    "pan",
    "detachable_triple_box",
    "single_shot",
    "none",
]
"""How rounds are held and fed."""

FIREARM_MAGAZINE_TYPES: Tuple[FirearmMagazineType, ...] = (
    "detachable_box",
    "detachable_single_stack_box",
    "fixed_box",
    "internal",
    "drum",
    "belt",
    "belt_fed",
    "disintegrating_link_belt",
    "tube",
    "tubular",
    "dual_tubular",
    "rotary",
    "revolving_cylinder",
    "helical",
    "en_bloc_clip",
    "stripper_clip",
    "internal_box",
    "integral",
    "feed_strip",
    "pan",
    "detachable_triple_box",
    "single_shot",
    "none",
)

AttachmentStatus = Literal[
    "in_production",
    "discontinued",
    "limited",
]
"""Production status of an attachment. `limited` corresponds to a firearm's `limited_production`."""

ATTACHMENT_STATUSES: Tuple[AttachmentStatus, ...] = (
    "in_production",
    "discontinued",
    "limited",
)

MediaKind = Literal[
    "silhouette",
    "render",
    "photo",
    "schematic",
    "model",
]
"""What kind of asset a media row is."""

MEDIA_KINDS: Tuple[MediaKind, ...] = (
    "silhouette",
    "render",
    "photo",
    "schematic",
    "model",
)

MediaItemKind = Literal[
    "silhouette",
    "render",
    "photo",
    "schematic",
    "model",
    "feature_icon",
]
"""What kind of asset a media listing item is: a stored kind, or `feature_icon`, the drawn icon for one of the firearm's features."""

MEDIA_ITEM_KINDS: Tuple[MediaItemKind, ...] = (
    "silhouette",
    "render",
    "photo",
    "schematic",
    "model",
    "feature_icon",
)

ImageType = Literal[
    "svg",
    "photo",
    "3d_model",
    "gallery",
    "primary",
    "thumbnail",
    "render",
    "profile",
    "angle",
    "detail",
]
"""The storage label on `FirearmImage.type`, predating `kind`: `svg` is `silhouette`, `3d_model` is `model`, and `gallery` is the default an upload lands on. Branch on `kind`."""

IMAGE_TYPES: Tuple[ImageType, ...] = (
    "svg",
    "photo",
    "3d_model",
    "gallery",
    "primary",
    "thumbnail",
    "render",
    "profile",
    "angle",
    "detail",
)

SchematicType = Literal[
    "blueprint",
    "spec_sheet",
    "manual",
    "datasheet",
    "exploded_view",
    "reference",
]
"""What a schematic document is."""

SCHEMATIC_TYPES: Tuple[SchematicType, ...] = (
    "blueprint",
    "spec_sheet",
    "manual",
    "datasheet",
    "exploded_view",
    "reference",
)

TicketStatus = Literal[
    "open",
    "in_progress",
    "waiting",
    "resolved",
    "closed",
]
"""Lifecycle of a support ticket. `waiting` means we are waiting on the customer."""

TICKET_STATUSES: Tuple[TicketStatus, ...] = (
    "open",
    "in_progress",
    "waiting",
    "resolved",
    "closed",
)

TicketPriority = Literal[
    "low",
    "normal",
    "high",
    "urgent",
]
"""Support ticket priority."""

TICKET_PRIORITIES: Tuple[TicketPriority, ...] = (
    "low",
    "normal",
    "high",
    "urgent",
)

TicketCategory = Literal[
    "billing",
    "technical",
    "data_quality",
    "feature_request",
    "other",
]
"""What a support ticket is about."""

TICKET_CATEGORIES: Tuple[TicketCategory, ...] = (
    "billing",
    "technical",
    "data_quality",
    "feature_request",
    "other",
)

ReportIssueType = Literal[
    "incorrect",
    "missing",
    "outdated",
]
"""What a data report says is wrong."""

REPORT_ISSUE_TYPES: Tuple[ReportIssueType, ...] = (
    "incorrect",
    "missing",
    "outdated",
)

ReportStatus = Literal[
    "pending",
    "reviewed",
    "resolved",
    "dismissed",
]
"""Lifecycle of a data report."""

REPORT_STATUSES: Tuple[ReportStatus, ...] = (
    "pending",
    "reviewed",
    "resolved",
    "dismissed",
)

UpdateKind = Literal[
    "catalog",
    "platform",
    "policy",
    "company",
    "incident",
]
"""What a site update is about: the catalogue, the platform, a policy, the company, or an incident."""

UPDATE_KINDS: Tuple[UpdateKind, ...] = (
    "catalog",
    "platform",
    "policy",
    "company",
    "incident",
)

UpdateBlockType = Literal[
    "paragraph",
    "heading",
    "list",
    "quote",
    "code",
    "figure",
]
"""The kind of block in a site update body. Each maps to a renderer on the website."""

UPDATE_BLOCK_TYPES: Tuple[UpdateBlockType, ...] = (
    "paragraph",
    "heading",
    "list",
    "quote",
    "code",
    "figure",
)

UpdateGlyphPattern = Literal[
    "impact",
    "ballistics",
    "rounds",
    "sweep",
    "waves",
    "thread",
    "lattice",
    "words",
]
"""A character-field pattern an update may name in place of a photograph. The website draws it."""

UPDATE_GLYPH_PATTERNS: Tuple[UpdateGlyphPattern, ...] = (
    "impact",
    "ballistics",
    "rounds",
    "sweep",
    "waves",
    "thread",
    "lattice",
    "words",
)

InterfaceSource = Literal[
    "curated",
    "inferred",
    "inherited:parent",
    "inherited:platform",
]
"""Where an interface row on a firearm came from. `curated` is a person; `inferred` is the backfill, capped at 0.6 confidence; the inherited kinds came through the parent chain or a platform."""

INTERFACE_SOURCES: Tuple[InterfaceSource, ...] = (
    "curated",
    "inferred",
    "inherited:parent",
    "inherited:platform",
)

FitType = Literal[
    "direct",
    "adapter",
    "curated",
]
"""How a fit was reached: on the firearm's own interface, through one adapter, or by a curated override."""

FIT_TYPES: Tuple[FitType, ...] = (
    "direct",
    "adapter",
    "curated",
)

FitSource = Literal[
    "curated",
    "universal",
    "inferred",
    "inherited:parent",
    "inherited:platform",
]
"""The weakest evidence behind a fit. A retailer or engineering consumer should treat `inferred` as unverified; `min_confidence` hides it."""

FIT_SOURCES: Tuple[FitSource, ...] = (
    "curated",
    "universal",
    "inferred",
    "inherited:parent",
    "inherited:platform",
)

SourceKind = Literal[
    "manufacturer",
    "standards_body",
    "government",
    "peer_reviewed",
    "reference",
    "aggregator",
    "press",
    "retailer",
    "community",
    "other",
]
"""What kind of page a cited source is, strongest first: the maker's own page, a standards body (SAAMI, C.I.P.), a government or military document, an independent reference work, a specification aggregator, the press, a retailer or auction listing, a community site, or an unclassified page. Weigh a figure by the best kind behind it, never by how many pages were cited."""

SOURCE_KINDS: Tuple[SourceKind, ...] = (
    "manufacturer",
    "standards_body",
    "government",
    "peer_reviewed",
    "reference",
    "aggregator",
    "press",
    "retailer",
    "community",
    "other",
)

GameArchetype = Literal[
    "sniper",
    "assault",
    "tank",
    "glass-cannon",
    "all-rounder",
    "support",
    "stealth",
    "speedster",
]
"""The role a firearm's game profile assigns it."""

GAME_ARCHETYPES: Tuple[GameArchetype, ...] = (
    "sniper",
    "assault",
    "tank",
    "glass-cannon",
    "all-rounder",
    "support",
    "stealth",
    "speedster",
)

ChangelogCategory = Literal[
    "feature",
    "improvement",
    "bugfix",
    "data",
    "breaking",
]
"""What kind of change a changelog entry records."""

CHANGELOG_CATEGORIES: Tuple[ChangelogCategory, ...] = (
    "feature",
    "improvement",
    "bugfix",
    "data",
    "breaking",
)

NoticeVariant = Literal[
    "info",
    "warning",
    "critical",
]
"""How prominently a site notice is shown."""

NOTICE_VARIANTS: Tuple[NoticeVariant, ...] = (
    "info",
    "warning",
    "critical",
)

OfferStatus = Literal[
    "draft",
    "published",
]
"""Whether a seller listing is public."""

OFFER_STATUSES: Tuple[OfferStatus, ...] = (
    "draft",
    "published",
)

OfferTargetKind = Literal[
    "attachment",
    "firearm",
]
"""What a seller listing is for."""

OFFER_TARGET_KINDS: Tuple[OfferTargetKind, ...] = (
    "attachment",
    "firearm",
)

AdoptionType = Literal[
    "military",
    "law_enforcement",
    "civilian",
    "paramilitary",
    "special_forces",
    "private_security",
    "training",
    "commercial",
    "government",
    "sporting",
    "tribal",
    "insurgent",
    "intelligence",
]
"""The kind of body that adopted a firearm."""

ADOPTION_TYPES: Tuple[AdoptionType, ...] = (
    "military",
    "law_enforcement",
    "civilian",
    "paramilitary",
    "special_forces",
    "private_security",
    "training",
    "commercial",
    "government",
    "sporting",
    "tribal",
    "insurgent",
    "intelligence",
)
