# GENERATED by scripts/sync_api_contracts.py from apps/api/src/schemas/webhooks.ts.
# Do not edit by hand: run `python scripts/sync_api_contracts.py` in packages/sdk-python.

from __future__ import annotations

from typing import Literal, Tuple

WebhookEventType = Literal[
    "firearm.created",
    "firearm.updated",
    "firearm.deleted",
    "firearm.variant.updated",
    "firearm.source.changed",
    "firearm.confidence.changed",
    "manufacturer.created",
    "manufacturer.updated",
    "manufacturer.deleted",
    "caliber.created",
    "caliber.updated",
    "caliber.deleted",
    "category.created",
    "category.updated",
    "category.deleted",
    "image.created",
    "image.deleted",
    "catalog.resynced",
]
"""Every event a webhook endpoint may subscribe to."""

WEBHOOK_EVENT_TYPES: Tuple[str, ...] = (
    "firearm.created",
    "firearm.updated",
    "firearm.deleted",
    "firearm.variant.updated",
    "firearm.source.changed",
    "firearm.confidence.changed",
    "manufacturer.created",
    "manufacturer.updated",
    "manufacturer.deleted",
    "caliber.created",
    "caliber.updated",
    "caliber.deleted",
    "category.created",
    "category.updated",
    "category.deleted",
    "image.created",
    "image.deleted",
    "catalog.resynced",
)


def is_webhook_event_type(value: object) -> bool:
    """Whether ``value`` is an event type the SDK recognises."""
    return isinstance(value, str) and value in WEBHOOK_EVENT_TYPES
